### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zavalacl/proj7#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by zavalacl** [comment]
It should all be fixed now! :)

https://arcane-ocean-2500.herokuapp.com/

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
